# Generated by Django 5.0 on 2024-01-06 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogger',
            name='fullname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
